[green_agent]
agentbeats_id = "019d76c2-3bb7-7652-b932-76ad868837b0"
env = {}

[[participants]]
agentbeats_id = "019e4ad7-0400-7701-96da-1c357b386fd9"
name = "agent"
env = {"AGENT_LLM": "DeepSeek-R1-Distill-Llama-70B" , ACADEMICCLOUD_API_KEY = "${ACADEMICCLOUD_API_KEY}" } 
